"""Database creation

Revision ID: f561ef529174
Revises: 
Create Date: 2024-11-13 18:51:44.489204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f561ef529174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallets_uuid', table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='wallets_pkey')
    )
    op.create_index('ix_wallets_uuid', 'wallets', ['uuid'], unique=False)
    # ### end Alembic commands ###
